---
title: "Lab 00 - Hello IDS!"
author: "michaela"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("lucy", "nicola", 
           "jay", "sherrill","crystal"),
  github_username = c("Lucy042915", "nicolahan", "jayphilipson", 
                      "Sherri1l", "craystal-suyue"), 
  colour = c("lightblue", "green", "green", 
             "blue", "white"),
  hobby = c("videogames","drawing", "knitting", 
            "videogames", "shootinggame"),
  favourite_number = c(1, 9, 7, 7, 5)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```


everyone's favourite numbers with the bars being in their favourite colour

### Exercises 19

Change the text of the plot title and axis labels.

```{r labelled-bar-plot}
p1 + labs(x = "github_username", 
          y = "favourite_number",
          title = "team_members_info")
```



### Exercise 20

```{r new-bar-plot}
p2 <- ggplot(team_data, aes(x = hobby)) +
  geom_bar()
p2
```

maybe a table is better to display this data
